<?php
/**
 * Implements hook_libraries_info().
 */
function riot_notifyjs_libraries_info() {
  $libraries = array();
  $libraries['notifyjs'] = array(
    'name' => 'NotifyJS',
    'vendor url' => 'https://notifyjs.com/',
    'download url' => 'https://github.com/notifyjs/notifyjs',
    'path' => 'dist',
    'version arguments' => array(
      'file' => 'bower.json',
      'pattern' => '/"version": (.+)/',
    ),
    'files' => array(
      'js' => array(
        'notify.js',
      ),
    ),
  );

  $libraries['notifyjs_metro_style'] = array(
    'name' => 'NotifyJS Style: Metro',
    'vendor url' => 'https://notifyjs.com/',
    'download url' => 'https://github.com/notifyjs/notifyjs',
    'version' => '1',
    'path' => 'dist/styles',
    'files' => array(
      'js' => array(
        'notify-metro.js',
      ), 
      'css' => array(
        'notify-metro.css',
      ),
    ),
    'dependencies' => array(
      'notifyjs'
    ),
  );

  $libraries['riot_notifyjs_mixin'] = array(
    'name' => 'RiotJS NotifyJS Mixin',
    'vendor url' => 'http://bluetent.com/',
    'download url' => 'https://bluetent.com/',
    'library path' => drupal_get_path('module', 'riot_notifyjs') . '/js',
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'mixin.js',
      ),
    ),
    'dependencies' => array(
      'riotjs',
      'notifyjs',
    ),
  );


  return $libraries;
}
